name: portfolio-CI

on:
  pull_request:
    branches: [ "main" ]
    types: 
      - closed
env:
  IMAGE_NAME: portfolio
  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}
          
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1.14.1
        with:
          url: ${{ secrets.PORTAINER_WEBHOOK_DEPLOY }}
          method: 'POST'
